info:
  name: update config
  type: http
  seq: 2

http:
  method: PATCH
  url: "{{base_url}}/user/config"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
