info:
  name: update config
  type: http
  seq: 2

http:
  method: PATCH
  url: "{{base_url}}/user/config"
  body:
    type: json
    data: |-
      {
         "personalized_prompt": "I like bananas" 
      }
  auth:
    type: bearer
    token: "{{bearer_token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
