# spike protection (5 per sec)
limit_req_zone $binary_remote_addr zone=api_burst:10m rate=5r/s;

# sustained spam protection (60 per min)
limit_req_zone $binary_remote_addr zone=api_sustained:10m rate=60r/m;

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        limit_req zone=api_burst burst=10 nodelay;
        limit_req zone=api_sustained burst=20 nodelay;
        limit_req_status 429;

        proxy_pass http://backend:8000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}